name: watermelon
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - pdfminer.six
  - pdfminer
  - pdfplumber==0.7.6
  - numpy==1.23.5
  - pandas==1.5.2
  - requests==2.28.1
  - beautifulsoup4==4.11.1
  - ipykernel==6.19.2
  - ipywidgets>=7.0
  - os==2.1.4
  - openpyxl==3.0.10
  - langdetect==1.0.9
  - transformers==4.24.0
  - sklearn==0.0.post1
  - scikit-learn==1.1.3
  - torch==1.13.0
  - torchtext==0.14.0
  - matplotlib==3.6.2
  - babel==2.11.0
  - tqdm==4.64.1
  - xgboost==1.7.2
  - nltk==3.7
  - Cython==0.29.28 
  - gensim==4.2.0 
  - smart-open==6.3.0
  - lis==0.7.9 
  - catalogue==2.0.8 
  - confection==0.0.3 
  - cymem==2.0.7 
  - langcodes==3.3.0 
  - murmurhash==1.0.9 
  - pathy==0.10.1 
  - preshed==3.0.8 
  - pydantic==1.10.2 
  - spacy==3.4.3 
  - spacy-legacy==3.0.10 
  - spacy-loggers==1.0.4 
  - srsly==2.4.5 
  - thinc==8.1.5 
  - typer==0.7.0 
  - wasabi==0.10.1
  