name: watermelon
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - pdfminer.six
  - pdfminer
  - pdfplumber==0.7.6
  - numpy==1.23.5
  - pandas==1.5.2
  - requests==2.28.1
  - beautifulsoup4==4.11.1
  - ipykernel==6.17.1
  - os==2.1.4
  - openpyxl==3.0.10